name: CI Pipeline

run-name: ${{ github.actor }} has initiated the run.

on:
  push:

jobs:
  Pushing-To-Main:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - run: echo "This will run only on main"
      - run: echo "Triggered by a ${{ github.event_name }} event."
      - run: echo "Running on a ${{ runner.os }} server"
      - run: echo "Branch is ${{ github.ref }}, repo is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: List files in the repository
        run: ls ${{ github.workspace }}
      - run: echo "Job status is ${{ job.status }}."

  Pushing-To-Not-Main:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - run: echo "This will run on branches that are not main"
      - run: echo "Triggered by a ${{ github.event_name }} event."
      - run: echo "Running on a ${{ runner.os }} server"
      - run: echo "Branch is ${{ github.ref }}, repo is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: List files in the repository
        run: ls ${{ github.workspace }}
      - run: echo "Job status is ${{ job.status }}."
