name: CI Pipeline

run-name: ${{ github.actor }} has initiated the run.

on:
  push:
  branches:
    - main

jobs:
  Pushing-To-Main:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This will run only on main"
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server"
      - run: echo "The name of branch is ${{ github.ref }} and the repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "Job status is ${{ job.status }}."

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  Pushing-To-Not-Main:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This will run branches that are not main"
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server"
      - run: echo "The name of branch is ${{ github.ref }} and the repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "Job status is ${{ job.status }}."
